name: dobrosport
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  carousel_slider: ^4.2.1
  go_router: ^11.0.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  freezed: ^2.4.2
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  syncfusion_flutter_charts: ^23.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SuisseIntl
      fonts:
        - asset: assets/font/SuisseIntl/SuisseIntl-Regular.otf
          weight: 400
        - asset: assets/font/SuisseIntl/SuisseIntl-Medium.otf
          weight: 500
        - asset: assets/font/SuisseIntl/SuisseIntl-SemiBold.otf
          weight: 600
        - asset: assets/font/SuisseIntl/SuisseIntl-Bold.otf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_icon.png'

flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image_android: 'assets/images/splash_android_12.png'
  image_dark_android: 'assets/images/splash_android_12.png'
  image_ios: 'assets/images/splash.png'
  image_dark_ios: 'assets/images/splash.png'
  branding_android: 'assets/images/splash_branding.png'
  branding_dark_android: 'assets/images/splash_branding.png'
  android_12:
    image: 'assets/images/splash_android_12.png'
    image_dark: 'assets/images/splash_android_12.png'
    branding: 'assets/images/splash_branding.png'